export const NIST_CONTROLS = [
  { id: 'AC-1', name: 'Access Control Policy and Procedures' },
  { id: 'AC-2', name: 'Account Management' },
  { id: 'AC-3', name: 'Access Enforcement' },
  { id: 'AC-4', name: 'Information Flow Enforcement' },
  { id: 'AC-5', name: 'Separation of Duties' },
  { id: 'AC-6', name: 'Least Privilege' },
  { id: 'AC-7', name: 'Unsuccessful Logon Attempts' },
  { id: 'AC-8', name: 'System Use Notification' },
  { id: 'AC-10', name: 'Concurrent Session Control' },
  { id: 'AC-11', name: 'Device Lock' },
  { id: 'AC-12', name: 'Session Termination' },
  { id: 'AC-14', name: 'Permitted Actions without Identification or Authentication' },
  { id: 'AC-17', name: 'Remote Access' },
  { id: 'AC-18', name: 'Wireless Access' },
  { id: 'AC-19', name: 'Access Control for Mobile Devices' },
  { id: 'AC-20', name: 'Use of External Systems' },
  { id: 'AC-21', name: 'User-Based Collaboration and Information Sharing' },
  { id: 'AC-22', name: 'Publicly Accessible Content' },
  { id: 'AT-1', name: 'Awareness and Training Policy and Procedures' },
  { id: 'AT-2', name: 'Literacy Training and Awareness' },
  { id: 'AT-3', name: 'Role-Based Training' },
  { id: 'AT-4', name: 'Training Records' },
  { id: 'AU-1', name: 'Audit and Accountability Policy and Procedures' },
  { id: 'AU-2', name: 'Event Logging' },
  { id: 'AU-3', name: 'Content of Audit Records' },
  { id: 'AU-4', name: 'Audit Storage Capacity' },
  { id: 'AU-5', name: 'Response to Audit Logging Process Failures' },
  { id: 'AU-6', name: 'Audit Record Review, Analysis, and Reporting' },
  { id: 'AU-7', name: 'Audit Record Reduction and Report Generation' },
  { id: 'AU-8', name: 'Time Stamps' },
  { id: 'AU-9', name: 'Protection of Audit Information' },
  { id: 'AU-10', name: 'Non-Repudiation' },
  { id: 'AU-11', name: 'Audit Record Retention' },
  { id: 'AU-12', name: 'Audit Record Generation' },
  { id: 'CA-1', name: 'Assessment, Authorization, and Monitoring Policy and Procedures' },
  { id: 'CA-2', name: 'Control Assessments' },
  { id: 'CA-3', name: 'Information Exchange' },
  { id: 'CA-5', name: 'Plan of Action and Milestones' },
  { id: 'CA-6', name: 'Authorization' },
  { id: 'CA-7', name: 'Continuous Monitoring' },
  { id: 'CA-8', name: 'Penetration Testing' },
  { id: 'CA-9', name: 'Internal System Connections' },
  { id: 'CM-1', name: 'Configuration Management Policy and Procedures' },
  { id: 'CM-2', name: 'Baseline Configuration' },
  { id: 'CM-3', name: 'Configuration Change Control' },
  { id: 'CM-4', name: 'Impact Analysis' },
  { id: 'CM-5', name: 'Access Restrictions for Change' },
  { id: 'CM-6', name: 'Configuration Settings' },
  { id: 'CM-7', name: 'Least Functionality' },
  { id: 'CM-8', name: 'System Component Inventory' },
  { id: 'CM-9', name: 'Configuration Management Plan' },
  { id: 'CM-10', name: 'Software Usage Restrictions' },
  { id: 'CM-11', name: 'User-Installed Software' },
  { id: 'CP-1', name: 'Contingency Planning Policy and Procedures' },
  { id: 'CP-2', name: 'Contingency Plan' },
  { id: 'CP-3', name: 'Contingency Training' },
  { id: 'CP-4', name: 'Contingency Plan Testing' },
  { id: 'CP-6', name: 'Alternate Storage Site' },
  { id: 'CP-7', name: 'Alternate Processing Site' },
  { id: 'CP-8', name: 'Telecommunications Services' },
  { id: 'CP-9', name: 'System Backup' },
  { id: 'CP-10', name: 'System Recovery and Reconstitution' },
  { id: 'IA-1', name: 'Identification and Authentication Policy and Procedures' },
  { id: 'IA-2', name: 'Identification and Authentication (Organizational Users)' },
  { id: 'IA-3', name: 'Device Identification and Authentication' },
  { id: 'IA-4', name: 'Identifier Management' },
  { id: 'IA-5', name: 'Authenticator Management' },
  { id: 'IA-6', name: 'Authentication Feedback' },
  { id: 'IA-7', name: 'Cryptographic Module Authentication' },
  { id: 'IA-8', name: 'Identification and Authentication (Non-Organizational Users)' },
  { id: 'IA-11', name: 'Re-Authentication' },
  { id: 'IA-12', name: 'Adaptive Authentication' },
  { id: 'IR-1', name: 'Incident Response Policy and Procedures' },
  { id: 'IR-2', name: 'Incident Response Training' },
  { id: 'IR-3', name: 'Incident Response Testing' },
  { id: 'IR-4', name: 'Incident Handling' },
  { id: 'IR-5', name: 'Incident Monitoring' },
  { id: 'IR-6', name: 'Incident Reporting' },
  { id: 'IR-7', name: 'Incident Response Assistance' },
  { id: 'IR-8', name: 'Incident Response Plan' },
  { id: 'MA-1', name: 'Maintenance Policy and Procedures' },
  { id: 'MA-2', name: 'Controlled Maintenance' },
  { id: 'MA-3', name: 'Maintenance Tools' },
  { id: 'MA-4', name: 'Nonlocal Maintenance' },
  { id: 'MA-5', name: 'Maintenance Personnel' },
  { id: 'MA-6', name: 'Timely Maintenance' },
  { id: 'MP-1', name: 'Media Protection Policy and Procedures' },
  { id: 'MP-2', name: 'Media Access' },
  { id: 'MP-3', name: 'Media Marking' },
  { id: 'MP-4', name: 'Media Storage' },
  { id: 'MP-5', name: 'Media Transport' },
  { id: 'MP-6', name: 'Media Sanitization' },
  { id: 'MP-7', name: 'Media Use' },
  { id: 'PE-1', name: 'Physical and Environmental Protection Policy and Procedures' },
  { id: 'PE-2', name: 'Physical Access Authorizations' },
  { id: 'PE-3', name: 'Physical Access Control' },
  { id: 'PE-4', name: 'Access Control for Transmission Medium' },
  { id: 'PE-5', name: 'Access Control for Output Devices' },
  { id: 'PE-6', name: 'Monitoring Physical Access' },
  { id: 'PE-8', name: 'Visitor Access Records' },
  { id: 'PE-9', name: 'Power Equipment and Cabling' },
  { id: 'PE-10', name: 'Emergency Shutoff' },
  { id: 'PE-11', name: 'Emergency Power' },
  { id: 'PE-12', name: 'Emergency Lighting' },
  { id: 'PE-13', name: 'Fire Protection' },
  { id: 'PE-14', name: 'Temperature and Humidity Controls' },
  { id: 'PE-15', name: 'Water Damage Protection' },
  { id: 'PE-16', name: 'Delivery and Removal' },
  { id: 'PE-17', name: 'Alternate Work Site' },
  { id: 'PE-18', name: 'Location of System Components' },
  { id: 'PL-1', name: 'Planning Policy and Procedures' },
  { id: 'PL-2', name: 'System Security and Privacy Plans' },
  { id: 'PL-4', name: 'Rules of Behavior' },
  { id: 'PL-8', name: 'Security and Privacy Architectures' },
  { id: 'PL-9', name: 'Central Management' },
  { id: 'PL-10', name: 'Baseline Selection' },
  { id: 'PL-11', name: 'Baseline Tailoring' },
  { id: 'PS-1', name: 'Personnel Security Policy and Procedures' },
  { id: 'PS-2', name: 'Position Risk Designation' },
  { id: 'PS-3', name: 'Personnel Screening' },
  { id: 'PS-4', name: 'Personnel Termination' },
  { id: 'PS-5', name: 'Personnel Transfer' },
  { id: 'PS-6', name: 'Access Agreements' },
  { id: 'PS-7', name: 'External Personnel Security' },
  { id: 'PS-8', name: 'Personnel Sanctions' },
  { id: 'RA-1', name: 'Risk Assessment Policy and Procedures' },
  { id: 'RA-2', name: 'Security Categorization' },
  { id: 'RA-3', name: 'Risk Assessment' },
  { id: 'RA-5', name: 'Vulnerability Monitoring and Scanning' },
  { id: 'RA-7', name: 'Risk Response' },
  { id: 'RA-9', name: 'Criticality Analysis' },
  { id: 'SA-1', name: 'System and Services Acquisition Policy and Procedures' },
  { id: 'SA-2', name: 'Allocation of Resources' },
  { id: 'SA-3', name: 'System Development Life Cycle' },
  { id: 'SA-4', name: 'Acquisition Process' },
  { id: 'SA-5', name: 'System Documentation' },
  { id: 'SA-8', name: 'Security and Privacy Engineering Principles' },
  { id: 'SA-9', name: 'External System Services' },
  { id: 'SA-10', name: 'Developer Configuration Management' },
  { id: 'SA-11', name: 'Developer Testing and Evaluation' },
  { id: 'SA-15', name: 'Development Process, Standards, and Tools' },
  { id: 'SA-16', name: 'Developer-Provided Training' },
  { id: 'SA-17', name: 'Developer Security and Privacy Architecture' },
  { id: 'SA-22', name: 'Unsupported System Components' },
  { id: 'SC-1', name: 'System and Communications Protection Policy and Procedures' },
  { id: 'SC-2', name: 'Separation of User Functionality and System Management Functionality' },
  { id: 'SC-3', name: 'Security Function Isolation' },
  { id: 'SC-4', name: 'Information in Shared System Resources' },
  { id: 'SC-5', name: 'Denial-of-Service Protection' },
  { id: 'SC-7', name: 'Boundary Protection' },
  { id: 'SC-8', name: 'Transmission Confidentiality and Integrity' },
  { id: 'SC-10', name: 'Network Disconnect' },
  { id: 'SC-12', name: 'Cryptographic Key Establishment and Management' },
  { id: 'SC-13', name: 'Cryptographic Protection' },
  { id: 'SC-15', name: 'Collaborative Computing Devices' },
  { id: 'SC-17', name: 'Public Key Infrastructure Certificates' },
  { id: 'SC-18', name: 'Mobile Code' },
  { id: 'SC-20', name: 'Secure Name / Address Resolution Service (Authoritative Source)' },
  { id: 'SC-21', name: 'Secure Name / Address Resolution Service (Recursive or Caching Resolver)' },
  { id: 'SC-22', name: 'Architecture and Provisioning for Name / Address Resolution Service' },
  { id: 'SC-23', name: 'Session Authenticity' },
  { id: 'SC-28', name: 'Protection of Information at Rest' },
  { id: 'SC-39', name: 'Process Isolation' },
  { id: 'SI-1', name: 'System and Information Integrity Policy and Procedures' },
  { id: 'SI-2', name: 'Flaw Remediation' },
  { id: 'SI-3', name: 'Malicious Code Protection' },
  { id: 'SI-4', name: 'Information System Monitoring' },
  { id: 'SI-5', name: 'Security Alerts, Advisories, and Directives' },
  { id: 'SI-7', name: 'Software, Firmware, and Information Integrity' },
  { id: 'SI-8', name: 'Spam Protection' },
  { id: 'SI-10', name: 'Information Input Validation' },
  { id: 'SI-11', name: 'Error Handling' },
  { id: 'SI-12', name: 'Information Management and Retention' },
  { id: 'SI-16', name: 'Memory Protection' },
  { id: 'SR-1', name: 'Supply Chain Risk Management Policy and Procedures' },
  { id: 'SR-2', name: 'Supply Chain Risk Management Plan' },
  { id: 'SR-3', name: 'Supply Chain Controls and Processes' },
  { id: 'SR-5', name: 'Acquisition Strategies, Tools, and Methods' },
  { id: 'SR-6', name: 'Supplier Assessments and Reviews' },
  { id: 'SR-8', name: 'Notification Agreements' },
  { id: 'SR-9', name: 'Tamper Resistance and Detection' },
  { id: 'SR-10', name: 'Inspection of Systems or Components' },
  { id: 'SR-11', name: 'Component Authenticity' },
  { id: 'SR-12', name: 'Component Disposal' },
];
